# Generated by Django 4.1.1 on 2022-12-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=50, verbose_name='Nombre de Institución')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('telefono', models.IntegerField(verbose_name='Teléfono')),
                ('fechainscrito', models.DateField()),
                ('institucion', models.CharField(max_length=50)),
                ('horainscrito', models.TimeField()),
                ('estado', models.IntegerField(choices=[[0, 'RESERVADO'], [1, 'COMPLETADA'], [2, 'ANULADA'], [3, 'NO ASISTE']], verbose_name='Estado')),
                ('observaciones', models.TextField(max_length=255, verbose_name='Observaciones')),
            ],
        ),
    ]
