# Generated by Django 4.1.1 on 2022-12-18 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='institucion',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='Reservas.institucion'),
        ),
    ]
